[package]
name = "polkaj-schnorrkel"
version = "0.3.0"

[lib]
crate_type = ["cdylib"]

[dependencies]
robusta_jni = "0.2"
jni = "0.21.1"
schnorrkel = "0.11.4"
hex = "0.4.2"
rand = "0.8.5"
merlin = "3.0"